/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVuelosRouteImport } from './routes/_authenticated/vuelos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVuelosIndexRouteImport } from './routes/_authenticated/vuelos.index'
import { Route as AuthenticatedVuelosNuevoRouteImport } from './routes/_authenticated/vuelos.nuevo'
import { Route as AuthenticatedVuelosIdRouteImport } from './routes/_authenticated/vuelos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVuelosRoute = AuthenticatedVuelosRouteImport.update({
  id: '/vuelos',
  path: '/vuelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVuelosIndexRoute =
  AuthenticatedVuelosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVuelosRoute,
  } as any)
const AuthenticatedVuelosNuevoRoute =
  AuthenticatedVuelosNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AuthenticatedVuelosRoute,
  } as any)
const AuthenticatedVuelosIdRoute = AuthenticatedVuelosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVuelosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vuelos': typeof AuthenticatedVuelosRouteWithChildren
  '/vuelos/$id': typeof AuthenticatedVuelosIdRoute
  '/vuelos/nuevo': typeof AuthenticatedVuelosNuevoRoute
  '/vuelos/': typeof AuthenticatedVuelosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vuelos/$id': typeof AuthenticatedVuelosIdRoute
  '/vuelos/nuevo': typeof AuthenticatedVuelosNuevoRoute
  '/vuelos': typeof AuthenticatedVuelosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vuelos': typeof AuthenticatedVuelosRouteWithChildren
  '/_authenticated/vuelos/$id': typeof AuthenticatedVuelosIdRoute
  '/_authenticated/vuelos/nuevo': typeof AuthenticatedVuelosNuevoRoute
  '/_authenticated/vuelos/': typeof AuthenticatedVuelosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/vuelos'
    | '/vuelos/$id'
    | '/vuelos/nuevo'
    | '/vuelos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/vuelos/$id'
    | '/vuelos/nuevo'
    | '/vuelos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/vuelos'
    | '/_authenticated/vuelos/$id'
    | '/_authenticated/vuelos/nuevo'
    | '/_authenticated/vuelos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vuelos': {
      id: '/_authenticated/vuelos'
      path: '/vuelos'
      fullPath: '/vuelos'
      preLoaderRoute: typeof AuthenticatedVuelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vuelos/': {
      id: '/_authenticated/vuelos/'
      path: '/'
      fullPath: '/vuelos/'
      preLoaderRoute: typeof AuthenticatedVuelosIndexRouteImport
      parentRoute: typeof AuthenticatedVuelosRoute
    }
    '/_authenticated/vuelos/nuevo': {
      id: '/_authenticated/vuelos/nuevo'
      path: '/nuevo'
      fullPath: '/vuelos/nuevo'
      preLoaderRoute: typeof AuthenticatedVuelosNuevoRouteImport
      parentRoute: typeof AuthenticatedVuelosRoute
    }
    '/_authenticated/vuelos/$id': {
      id: '/_authenticated/vuelos/$id'
      path: '/$id'
      fullPath: '/vuelos/$id'
      preLoaderRoute: typeof AuthenticatedVuelosIdRouteImport
      parentRoute: typeof AuthenticatedVuelosRoute
    }
  }
}

interface AuthenticatedVuelosRouteChildren {
  AuthenticatedVuelosIdRoute: typeof AuthenticatedVuelosIdRoute
  AuthenticatedVuelosNuevoRoute: typeof AuthenticatedVuelosNuevoRoute
  AuthenticatedVuelosIndexRoute: typeof AuthenticatedVuelosIndexRoute
}

const AuthenticatedVuelosRouteChildren: AuthenticatedVuelosRouteChildren = {
  AuthenticatedVuelosIdRoute: AuthenticatedVuelosIdRoute,
  AuthenticatedVuelosNuevoRoute: AuthenticatedVuelosNuevoRoute,
  AuthenticatedVuelosIndexRoute: AuthenticatedVuelosIndexRoute,
}

const AuthenticatedVuelosRouteWithChildren =
  AuthenticatedVuelosRoute._addFileChildren(AuthenticatedVuelosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVuelosRoute: typeof AuthenticatedVuelosRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedVuelosRoute: AuthenticatedVuelosRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
